const DATA = [
    {
      id: '1',
      title: 'Chicken BBQ pizza',
      variants: '2 variants',
      category: 'Pizza',
      image:
        'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      available: true,
      desc: 'Pizza meal combo with grated cheese and vegetables party',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!',
      image1:
        'https://imgs.search.brave.com/NvFgj_DF5EtckQNzI3wEhU18_luJnP147myw8Wlp5yg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTc0/ODQ2NDAxL3Bob3Rv/L3BpenphLWFzc29y/dG1lbnQuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPWNKUnpQ/TmxSSHNfN2NsSzZq/UlhjclZmOFUxaEFV/c3lCM2oxYXo0RE1L/dFk9',
      value: 'SAR 200.00',
      kcal: '360 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '2',
      title: 'French fries combo',
      // variants: '2 variants',
      category: 'Favourite',
      image:
        'https://s.yimg.com/ny/api/res/1.2/ayVo_1.k3lhURG9FtnXz2Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTE1NjA7aD04NzY7Y2Y9d2VicA--/https://media.zenfs.com/en/the_daily_meal_185/e68c815071adf1727198cdfdff4ab154',
      available: true,
      desc: 'French fries. The crispy crown of culinary perfection.',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        "Golden and crispy fries, perfectly seasoned and fried to perfection. A classic comfort snack that's irresistible and satisfying with every bite!",
      value: 'SAR 500.00',
      kcal: '300 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '3',
      title: 'Pan pizza',
      variants: '2 variants',
      category: 'Sandwich',
      image:
        'https://imgs.search.brave.com/V0Ey37afqIsEZj8zv-CO0yBLdnhGp8eMHP7OhYm02Ak/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c2VyaW91c2VhdHMu/Y29tL3RobWIvdG5G/VnNYUmVRSHo5Zksw/WFhXd016YXNsYXZJ/PS8xNTAweDAvZmls/dGVyczpub191cHNj/YWxlKCk6bWF4X2J5/dGVzKDE1MDAwMCk6/c3RyaXBfaWNjKCkv/X19vcHRfX2Fib3V0/Y29tX19jb2V1c19f/cmVzb3VyY2VzX19j/b250ZW50X21pZ3Jh/dGlvbl9fc2VyaW91/c19lYXRzX19zZXJp/b3VzZWF0cy5jb21f/XzIwMTlfXzA0X18y/MDE5MDMxOS1jYXN0/LWlyb24tcGFuLXBp/enphLXJlc2hvb3Qt/dmlja3ktd2FzaWst/MjktMzMzMTcwZDM2/YzAwNGY1YmJmZWVk/M2FkOTc0MzcwNzgu/anBn', // Replace with actual image URL
      available: true,
      desc: 'You cannot make everyone happy, but you can make pizza and that is kind of the same thing.',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!',
      value: 'SAR 300.00',
      kcal: '400 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '4',
      title: 'Mushroom Sandwich',
      variants: 'Unavailable',
      category: 'Sandwich',
      image:
        'https://imgs.search.brave.com/RxB7MDC0J9u8j8pYpWmB6Jf6ocT6z8gnYoi5Hss7bpI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dGhlc3BydWNlZWF0/cy5jb20vdGhtYi9D/dXBvX1dDcWEyQlpD/YTB2LWJHVXg2NHBr/YVk9LzE1MDB4MC9m/aWx0ZXJzOm5vX3Vw/c2NhbGUoKTptYXhf/Ynl0ZXMoMTUwMDAw/KTpzdHJpcF9pY2Mo/KS9jcmlzcHktZnJp/ZWQtbXVzaHJvb20t/c2FuZHdpY2gtNzU2/MTMxNC1Kb2FuLVZl/bHVzaC0yMDIzLWFl/OGE3MWIzNWI3NTRm/MTZhZmViZTYwODNl/NDBkZWM1LmpwZWc',
      available: false,
      desc: 'A sandwich is a little piece of happiness you can hold in your hands.',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'A hearty sandwich filled with sautéed mushrooms, melted cheese, and seasoned to perfection. A savory delight for all mushroom lovers!',
      value: 'SAR 100.00',
      kcal: '450 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '5',
      title: 'Watermelon juice',
      // variants: '2 variants',
      category: 'Juice',
      image:
        'https://imgs.search.brave.com/RO23rdepAS0ZJwUt0Jc5oGocbugDbO_bUxUBhfGWNhk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9mYW1p/bHlzcGljZS5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMTQv/MDcvd2F0ZXJtZWxv/bl9qdWljZV82ODAu/anBn', // Replace with actual image URL
      available: true,
      desc: 'Sip into summer with a splash of watermelon magic!',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Chilled and refreshing watermelon juice, bursting with natural sweetness. A hydrating treat that quenches your thirst and invigorates your senses with every sip!',
      value: 'SAR 150.00',
      kcal: '200 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '6',
      title: 'Plain Nachos',
      variants: '2 variants',
      category: 'Burger',
      image:
        'https://imgs.search.brave.com/i_rcDF_0qbucXVGepDFrMjVm1TOYioyaIxFNKLtbcFY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDY0/OTk2MDg2L3Bob3Rv/L2hvbWVtYWRlLW5h/Y2hvcy13aXRoLWNo/ZWRkYXItY2hlZXNl/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz1RbUZJTkt6bmpv/YWJWakVnZXhJUE1w/eVFLMjY0VndET3JV/UTdySWI3Ti1BPQ', // Replace with actual image URL
      available: true,
      desc: "Nacho average snack, it's a party on a plate!",
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Crispy tortilla chips generously loaded with melted cheese and topped with zesty jalapeños. A perfect blend of flavors that brings the fiesta to your plate!',
      value: 'SAR 100.00',
      kcal: '100 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '7',
      title: 'Mexican Nachos with salsa',
      variants: 'Out of stock',
      category: 'Sandwich',
      image:
        'https://imgs.search.brave.com/iu8bDFnUnVgCPZ_oYYwy4Il6r3wHfRUP_4VOk9ovU9o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQ2/MzExNzA4Ni9waG90/by9zaHJpbXAtbmFj/aG9zLXdpdGgtamFs/YXBlbm9zLmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz00bzFr/NktUMFZkVklkenBo/ZVRscVE5UEFORTV0/eGhYN0g0LU9jWVN0/OU1BPQ', // Replace with actual image URL
      available: false,
      desc: "Nachos so good, you'll melt with every bite.",
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Indulge in a plate of our crispy Mexican Nachos, generously topped with melted cheese, fresh jalapeños, and a zesty salsa',
      value: 'SAR 250.00',
      kcal: '140 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '8',
      title: 'Grape juice',
      // variants: '2 variants',
      category: 'Juice',
      image:
        'https://imgs.search.brave.com/PrGJ_ywoOULNY3qh03r9cSMEQ1QaIxM5fm_XvjayHQI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTcx/MjUyODIwL3Bob3Rv/L2dyYXBlLWp1aWNl/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz04OVhOWVN4bVE1/TkVSNEdwbGF6TUZR/VEQwYjV3RTQwcUhj/UUNnTjlwREtNPQ', // Replace with actual image URL
      available: true,
      desc: 'Juicy vibes only! Grapes know how to keep it classy.',
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Experience the burst of flavor with our refreshing grape juice, crafted from the finest ripe grapes. Perfectly sweet and invigorating, its a delightful sip that captures the essence of summer in every drop.',
      value: 'SAR 350.00',
      kcal: '320 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
    {
      id: '9',
      title: 'Mango juice with salad',
      variants: 'Unavailable',
      category: 'Juice',
      image:
        'https://imgs.search.brave.com/ZJm15vOi6_f83trdMCdcv5wkS61LZcT5Nya_gZFVeQg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTg1/MDEyMjM0L3Bob3Rv/L21hbmdvLWp1aWNl/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz1vSDI3ZEZIaHVj/ck5nOF9SM1U2R1ho/ZkJvMExDVXFsVThy/bENiUWVDdTY4PQ', // Replace with actual image URL
      available: false,
      desc: "Sip the sunshine, taste the tropics . It's mango time!",
      size1: 'Small',
      price1: 'SAR 200.00',
      size2: 'Medium',
      price2: 'SAR 250.00',
      size3: 'Large',
      price3: 'SAR 300.00',
      description:
        'Savor the tropical essence of our Mango Juice, freshly squeezed to capture the sun-kissed sweetness of ripe mangoes',
      value: 'SAR 450.00',
      kcal: '999 Kcal',
      small: 'SAR 200.00',
      medium: 'SAR 250.00',
      large: 'SAR 300.00',
    },
  ];

  export default DATA;