import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  modalcontext: {
    padding: 20,
    width: '100%',
  },
  container: {
    color: 'rgb(239, 243, 246)',
  },
  boxx1: {
    width: '40%',
    paddingVertical: 15,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    borderColor: 'grey',
    borderWidth: 1.5,
    gap: 5,
    borderStyle: 'solid',
    borderRadius: 10,
  },
  boxx2: {
    width: '60%',
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    backgroundColor: 'rgb(18, 99, 223)',
    gap: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textt6: {
    color: 'white',
    fontWeight: '500',
    fontSize: 15,
  },
  textt7: {
    color: 'black',
    fontWeight: '900',
    fontSize: 15,
  },
  iconContainer: {
    position: 'absolute',
    top: 5,
    right: 5,
  },
  iconBackground: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: 25,
    height: 25,
  },
  iconContainer1: {
    position: 'absolute',
    top: 5,
    left: 75,
  },
  iconBackground1: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: 25,
    height: 25,
  },
  infoBox: {
    alignItems: 'center',
    // marginHorizontal: 5,
  },
  label: {
    marginLeft: 8,
  },
  box1: {
    width: '32%',
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    borderColor: 'grey',
    borderWidth: 1.5,
    gap: 5,
    borderStyle: 'solid',
    borderRadius: 10,
  },
  box2: {
    width: '65%',
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    backgroundColor: 'rgb(18, 99, 223)',
    gap: 5,
    // borderStyle: 'solid',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text6: {
    color: 'white',
    fontWeight: '500',
    fontSize: 15,
  },
  text7: {
    color: 'black',
    fontWeight: '900',
    fontSize: 15,
  },
  label: {
    color: 'black',
    fontSize: 16,
    paddingTop: 5,
  },
  grid: {
    padding: 10,
  },
  row1: {
    flexDirection: 'row',
    marginHorizontal: 20,
  },
  row3: {
    flexDirection: 'row',
  },
  arrowfront: {
    borderColor: 'black',
    borderWidth: 1.5,
    borderRadius: 15,
    padding: 3,
  },
  arrowfront1: {
    position: 'relative',
    backgroundColor: 'skyblue',
    borderRadius: 15,
    padding: 3,
  },
  button: {
    width: '100%',
  },
  additem: {
    color: 'white',
    fontWeight: 'bold',
    backgroundColor: 'rgb(18, 99, 223)',
    textAlign: 'center',
    padding: 15,
    borderRadius: 10,
  },
  item: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '32%',
    marginBottom: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  itemImage: {
    width: '100%',
    height: 80,
  },
  itemImage1: {
    width: '30%',
    height: 100,
    borderRadius: 10,
  },
  itemTextContainer: {
    padding: 10,
  },
  itemTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: 'black',
  },
  itemVariants: {
    fontSize: 12,
    color: 'grey',
  },
  unavailable: {
    opacity: 0.35,
  },
  unavailableText: {
    color: 'red',
    fontWeight: 'bold',
  },
  text1: {
    color: 'black',
    fontWeight: 'bold',
  },
  text11: {
    fontSize: 18,
    color: 'black',
    fontWeight: 'bold',
  },
  text2: {
    color: 'grey',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '100%',
    backgroundColor: 'rgb(239, 243, 246)',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    overflow: 'hidden',
    paddingBottom: 20,
  },
  modalContentt: {
    width: '100%',
    backgroundColor: 'rgb(239, 243, 246)',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    overflow: 'hidden',
    paddingTop: 10,
  },
  modalImage: {
    width: '100%',
    height: 200,
    marginBottom: 10,
  },
  modalText: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalTextt: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    color: 'rgb(18, 99, 223)',
  },
  modalText1: {
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    padding: 20,
    color: 'black',
  },
  variant: {
    width: '50%',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  variant1: {
    width: '50%',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  modalText2: {
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    padding: 15,
  },
  modalText3: {
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    padding: 15,
  },
  icon: {
    padding: 5,
    borderRadius: 20,
    backgroundColor: 'white',
    position: 'absolute',
    alignContent: 'flex-end',
    right: 10,
    top: 10,
  },
  line: {
    height: 1,
    backgroundColor: '#ccc',
    width: '100%',
    marginVertical: 20,
  },
  line1: {
    height: 1,
    backgroundColor: 'rgb(232,232,232)',
    width: '100%',
    marginVertical: 15,
  },
  line2: {
    height: 2.5,
    backgroundColor: 'rgb(228, 231, 234)',
    width: '100%',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  roww: {
    flexDirection: 'row',
    width: '100%',
  },
  roww1: {
    flexDirection: 'row',
    width: '100%',
    marginHorizontal: 10,
  },
  handle: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginLeft: 5,
    marginTop: 20,
  },
  variantstyle: {
    flexDirection: 'row',
    marginVertical: 10,
    width: '100%',
    justifyContent: 'space-between',
  },
});

export {styles};
